name: Partie 3
on: workflow_dispatch
# env:
#   Actor: ${{ github.actor }}
#   RunName: ${{ github.actor }} Fait la partie 3
#   Time: date +"%T"
#   Date: date +"%d-%m-%y"
jobs:
  e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # - name: Set github user
      #   run: git config user.email "test@example.com" && git config user.name "CI/CD"
      - name: Install the dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          npx playwright test --workers 4 --project=chromium --grep @smoke
          echo ::set-output name=status::$status
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     # #- name: Set up Node.js
  #     #   uses: actions/setup-node@v4
  #     #   with:
  #     #     node-version: ">=22"

  #     - name: Set github user
  #       run: git config user.email "test@example.com" && git config user.name "CI/CD - MMI"

  #     - name: Install dependencies
  #       run: npm ci

  #     #- name: Lint
  #     #  run: npm run lint

  #     #- name: Test
  #     #  run: npm run test

  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps

  #     - name: Run Playwright tests
  #       run: npx playwright test --project=chromium --grep @smoke

  #     # - name: Date et heure du build
  #     #   run: echo "Le build a été lancé le ${{ env.Date }} à ${{ env.Time }} par ${{ env.Actor }}"

  #     # - name: Build
  #     #   run: npm run build

  #     # - name: SSH
  #     #   run: |
  #     #     echo ${{ secrets.ACTION_SSH }} > ~/deployement_key && chmod 400 ~/deployement_key
  #     #     rsync -Pav -e "ssh -i ~/deployement_key -o StrictHostKeyChecking=no" ./git_action_P3/ ${{ secrets.USER_SSH}}@${{secrets.SERVER_SSH}}:/www/
