name: Merged with master
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 - ${{ github.ref }}

on:
  pull_request:
    types: [closed]

jobs:
  get_artifact:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"
      # - name: get last id
      #   shell: python
      #   run: |
      #     import os, requests, argparse

      #     env_file = os.getenv('GITHUB_ENV')

      #     headers = {
      #         'Accept': 'application/vnd.github+json',
      #         'Authorization': 'Bearer ${{ secrets.GITHUB_TOKEN }}',
      #         'X-GitHub-Api-Version': '2022-11-28',
      #     }
      #     req = requests.get(
      #         'https://api.github.com/repos/DanYellow/test/actions/runs?status=success&per_page=2&branch=test&event=pull_request',
      #         headers=headers
      #     )

      #     response = req.json()
      #     last_completed_run_id = response["workflow_runs"][0]["id"]
      #     with open(env_file, "a") as github_env:
      #       github_env.write(f"LAST_COMPLETED_RUN_ID={last_completed_run_id}")
