name: Download another artifact
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 - ${{ github.ref }}
on: workflow_dispatch

jobs:
    download_artifact:
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: bundle
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - run: ls -al
