name: Deploy master
run-name: ${{ github.actor }} is deploying to prod

on:
  workflow_dispatch:

jobs:
  define_env:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    outputs:
      VITE_LIST_COLLABORATORS: ${{ steps.test.outputs.VITE_LIST_COLLABORATORS }}
    steps:
      - run: |
          list_collaborators="$(gh api /repos/DanYellow/test/collaborators)"

          result='[]'
          for collaborator in `echo $list_collaborators | jq --raw-output -c '.[]'`; do
            login=`echo $collaborator | jq '.login'`
            user_request="$(gh api /users/$(echo $login | jq --raw-output))"

            collaborator="{}"
            html_url=`echo $user_request | jq '.html_url'`
            name=`echo $user_request | jq '.name'`

            collaborator="$(jq ".login=${login}" <<< "$collaborator")"
            collaborator="$(jq ".name=${name}" <<< "$collaborator")"
            collaborator="$(jq ".html_url=${html_url}" <<< "$collaborator")"

            # echo "$avatar_url"
            result="$(jq --argjson val "$collaborator" '. += [$val]' <<< "$result")"
          done

          echo "$result"
          str_result="$(jq '.| tostring' <<< "$result")"

          echo "VITE_LIST_COLLABORATORS=$str_result" >> "$GITHUB_OUTPUT"
        id: test
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: define_env
    runs-on: ubuntu-latest
    env:
      VITE_LIST_COLLABORATORS: ${{ needs.define_env.outputs.VITE_LIST_COLLABORATORS }}
      TEST: tedd
    steps:
      - run: echo "VITE_LIST_COLLABORATORS=${{ needs.define_env.outputs.VITE_LIST_COLLABORATORS }}" >> "$GITHUB_ENV"
      - run: echo "${{ env.TEST }}"
      - run: echo ${{ env.VITE_LIST_COLLABORATORS }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set github user
        run: git config --global user.email "test@example.com" && git config --global user.name "CI/CD"
      - name: Install the dependencies
        run: npm ci
      - run: |
          # echo "VITE_BUILD_DATE=$(date +'%d/%m/%Y %H:%M:%S')" >> $GITHUB_ENV
          echo "$VITE_BUILD_DATE"
          chmod +x ${{ github.workspace }}/copy.sh
          ${{ github.workspace }}/copy.sh ${{ github.workspace }}
      - name: Create build
        run: npm run build
      - name: Generate artifact
        uses: actions/upload-artifact@master
        with:
          name: bundle
          path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: bundle
      - name: Fill ssh key
        run: echo "${{secrets.SSH_KEY}}" > ~/deploy_key && chmod 400 ~/deploy_key
      - name: Move files
        run: rsync -Pavz -e "ssh -i ~/deploy_key -o StrictHostKeyChecking=no" ${{ github.workspace }}/ ${{ secrets.USER }}@${{ secrets.SERVER }}:~/www
