name: Download another artifact
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 - ${{ github.ref }}
on: workflow_dispatch

jobs:
    download_artifact:
      runs-on: ubuntu-latest
      steps:
        # - uses: actions/setup-python@v5
        #   with:
        #     python-version: '3.13'
        # - run: python get-lastprod.py --gh-token=${{ secrets.GITHUB_TOKEN }}
        - name: get last id
          shell: python
          run: |
            import os, requests, argparse

            env_file = os.getenv('GITHUB_ENV')

            parser = argparse.ArgumentParser()
            parser.add_argument(
                "--gh-token",
                help="Github token",
                type=str,
                default="",
                required=False
            )
            args = parser.parse_args()

            headers = {
                'Accept': 'application/vnd.github+json',
                'Authorization': f'Bearer {args["gh-token"]}',
                'X-GitHub-Api-Version': '2022-11-28',
            }
            req = requests.get(
                'https://api.github.com/repos/DanYellow/test/actions/workflows/133863234/runs?status=completed&per_page=2',
                headers=headers
            )

            response = req.json()

            with open(env_file, "a") as myfile:
                myfile.write(f"LAST_COMPLETED_RUN_ID={response.workflow_runs[0].id}")
        - run: echo ${{ env.LAST_COMPLETED_RUN_ID }}
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: bundle
            run-id: 12468380590
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - run: ls -al
